// frontend-demo/react-project/src/components/chart-card/chart-card.tsx
import { useEffect, useRef } from 'react'
import { Card, Spin } from 'antd'
import { Chart } from '@antv/g2'
import './chart-card.scss'

export type ChartBuilder = (chart: Chart) => void

interface ChartCardProps {
    title: string
    loading?: boolean
    height?: number
    data?: unknown
    buildChart: ChartBuilder
}

export default function ChartCard({
    title,
    loading = false,
    height = 320,
    data,
    buildChart,
}: ChartCardProps) {
    const containerRef = useRef<HTMLDivElement>(null)
    const chartRef = useRef<Chart | null>(null)

    useEffect(() => {
        if (!containerRef.current || data == null) return

        const chart = new Chart({
            container: containerRef.current,
            autoFit: true,
            height,
        })

        chart.data(data as never)
        buildChart(chart)
        chart.render()
        chartRef.current = chart

        const observer = new ResizeObserver(() => {
            chart.forceFit()
        })
        observer.observe(containerRef.current)

        return () => {
            observer.disconnect()
            chart.destroy()
            chartRef.current = null
        }
    }, [buildChart, data, height])

    return (
        <Card
            title={title}
            className="chart-card"
            styles={{ body: { paddingBottom: 8 } }}>
            <Spin spinning={loading}>
                <div
                    ref={containerRef}
                    className="chart-card__canvas"
                    style={{ minHeight: height }}
                />
            </Spin>
        </Card>
    )
}

// frontend-demo/vue-project/src/components/chart-card/chart-card.vue
<template>
    <a-card class="chart-card" :title="title" :body-style="{ padding: '8px 12px 4px' }">
        <a-spin :spinning="loading">
            <div
                ref="containerRef"
                class="chart-card__canvas"
                :style="{ minHeight: `${height}px` }" />
        </a-spin>
    </a-card>
</template>

<script lang="ts" setup>
    import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
    import { Chart } from '@antv/g2'

    type ChartBuilder = (chart: Chart) => void

    interface Props {
        title: string
        buildChart: ChartBuilder
        loading?: boolean
        height?: number
        data?: unknown
    }

    const props = withDefaults(defineProps<Props>(), {
        loading: false,
        height: 240,
        data: undefined,
    })

    const containerRef = ref<HTMLDivElement>()

    let chart: Chart | null = null
    let observer: ResizeObserver | null = null

    function destroyChart() {
        observer?.disconnect()
        observer = null
        chart?.destroy()
        chart = null
    }

    function renderChart() {
        if (!containerRef.value || props.data == null) return

        destroyChart()

        chart = new Chart({
            container: containerRef.value,
            autoFit: true,
            height: props.height,
        })
        chart.data(props.data as never)
        props.buildChart(chart)
        chart.render()

        observer = new ResizeObserver(() => chart?.forceFit())
        observer.observe(containerRef.value)
    }

    watch(() => [props.data, props.buildChart, props.height], renderChart)

    onMounted(renderChart)
    onBeforeUnmount(destroyChart)
</script>

<style lang="scss" scoped>
    .chart-card {
        height: 100%;
        border: 1px solid var(--admin-border);
        box-shadow: var(--admin-shadow);
        background: var(--admin-surface);

        :deep(.ant-card-head) {
            min-height: 40px;
            padding-block: 0;
            border-bottom-color: var(--admin-border);
            color: var(--admin-ink);
            font-size: 13px;
            font-weight: 600;
        }

        &__canvas {
            width: 100%;
        }
    }
</style>
