// frontend-demo/vue-project/src/layouts/admin-layout/admin-layout.vue
<template>
    <a-layout class="admin-layout">
        <a-layout-sider
            v-if="!isMobile"
            class="admin-layout__sider"
            collapsible
            :trigger="null"
            :collapsed="collapsed"
            :width="208"
            :collapsed-width="64">
            <BrandMark :collapsed="collapsed" />
            <a-menu
                class="admin-layout__menu"
                theme="dark"
                mode="inline"
                :selected-keys="selectedKeys"
                :items="menuItems"
                @click="handleMenuClick" />
        </a-layout-sider>

        <a-layout class="admin-layout__main">
            <a-layout-header class="admin-layout__header">
                <div class="admin-layout__header-left">
                    <a-button
                        type="text"
                        class="admin-layout__trigger"
                        @click="handleTrigger">
                        <template #icon>
                            <MenuUnfoldOutlined v-if="isMobile || collapsed" />
                            <MenuFoldOutlined v-else />
                        </template>
                    </a-button>
                    <div class="admin-layout__header-titles">
                        <span class="admin-layout__header-title">Vue 框架示例</span>
                        <span class="admin-layout__header-desc">前端工程化模板</span>
                    </div>
                </div>
            </a-layout-header>

            <a-layout-content class="admin-layout__content">
                <RouterView />
            </a-layout-content>
        </a-layout>

        <a-drawer
            title="菜单"
            placement="left"
            :width="260"
            :open="isMobile && mobileOpen"
            :body-style="{ padding: 0 }"
            @close="setMobileOpen(false)">
            <div class="admin-layout__drawer">
                <BrandMark />
                <a-menu
                    class="admin-layout__menu admin-layout__menu--light"
                    theme="light"
                    mode="inline"
                    :selected-keys="selectedKeys"
                    :items="menuItems"
                    @click="handleMenuClick" />
            </div>
        </a-drawer>
    </a-layout>
</template>

<script lang="ts" setup>
    import { computed, h, watch } from 'vue'
    import { useRoute, useRouter } from 'vue-router'
    import { storeToRefs } from 'pinia'
    import {
        DashboardOutlined,
        MenuFoldOutlined,
        MenuUnfoldOutlined,
        TableOutlined,
    } from '@ant-design/icons-vue'
    import type { ItemType } from 'ant-design-vue'
    import BrandMark from '@/components/brand-mark/brand-mark.vue'
    import { useResponsive } from '@/composables/useResponsive'
    import { useLayoutStore } from '@/stores'

    const menuItems: ItemType[] = [
        { key: '/dashboard', icon: () => h(DashboardOutlined), label: '仪表盘' },
        { key: '/demo/table', icon: () => h(TableOutlined), label: '示例表格' },
    ]

    const route = useRoute()
    const router = useRouter()
    const { isMobile } = useResponsive()

    const layoutStore = useLayoutStore()
    const { collapsed, mobileOpen } = storeToRefs(layoutStore)
    const { toggleCollapsed, setMobileOpen } = layoutStore

    const selectedKeys = computed(() => {
        const matched = menuItems.find(
            item => item && 'key' in item && route.path.startsWith(String(item.key)),
        )
        return [matched?.key ?? '/dashboard']
    })

    watch(isMobile, mobile => {
        if (!mobile) {
            setMobileOpen(false)
        }
    })

    function handleTrigger() {
        if (isMobile.value) {
            setMobileOpen(true)
        } else {
            toggleCollapsed()
        }
    }

    function handleMenuClick(info: { key: string | number }) {
        router.push(String(info.key))
        if (isMobile.value) {
            setMobileOpen(false)
        }
    }
</script>

<style lang="scss" scoped src="./admin-layout.scss"></style>

// frontend-demo/react-project/src/layouts/admin-layout/admin-layout.tsx
import { useEffect, useMemo } from 'react'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { Button, Drawer, Grid, Layout, Menu, Typography } from 'antd'
import {
    DashboardOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    TableOutlined,
} from '@ant-design/icons'
import { useLayoutStore } from '@/stores'
import './admin-layout.scss'

const { Header, Sider, Content } = Layout

const menuItems = [
    {
        key: '/dashboard',
        icon: <DashboardOutlined />,
        label: '仪表盘',
    },
    {
        key: '/demo/table',
        icon: <TableOutlined />,
        label: '示例表格',
    },
]

function BrandMark({ collapsed }: { collapsed?: boolean }) {
    return (
        <div
            className={`admin-layout__logo${collapsed ? ' admin-layout__logo--collapsed' : ''}`}>
            <span className="admin-layout__logo-mark" aria-hidden>
                R
            </span>
            {!collapsed ? (
                <div className="admin-layout__logo-copy">
                    <Typography.Text className="admin-layout__logo-title">
                        React Demo
                    </Typography.Text>
                    <Typography.Text className="admin-layout__logo-subtitle">
                        Framework
                    </Typography.Text>
                </div>
            ) : null}
        </div>
    )
}

export default function AdminLayout() {
    const navigate = useNavigate()
    const location = useLocation()
    const screens = Grid.useBreakpoint()
    const isMobile = !screens.lg

    const collapsed = useLayoutStore(state => state.collapsed)
    const mobileOpen = useLayoutStore(state => state.mobileOpen)
    const toggleCollapsed = useLayoutStore(state => state.toggleCollapsed)
    const setMobileOpen = useLayoutStore(state => state.setMobileOpen)

    useEffect(() => {
        if (!isMobile) {
            setMobileOpen(false)
        }
    }, [isMobile, setMobileOpen])

    const selectedKeys = useMemo(() => {
        const matched = menuItems.find(item => location.pathname.startsWith(item.key))
        return [matched?.key ?? '/dashboard']
    }, [location.pathname])

    const handleMenuClick = ({ key }: { key: string }) => {
        navigate(key)
        if (isMobile) {
            setMobileOpen(false)
        }
    }

    const sideMenu = (themeMode: 'light' | 'dark' = 'dark') => (
        <Menu
            className="admin-layout__menu"
            theme={themeMode}
            mode="inline"
            selectedKeys={selectedKeys}
            items={menuItems}
            onClick={handleMenuClick}
        />
    )

    return (
        <Layout className="admin-layout">
            {!isMobile && (
                <Sider
                    className="admin-layout__sider"
                    trigger={null}
                    collapsible
                    collapsed={collapsed}
                    width={208}
                    collapsedWidth={64}>
                    <BrandMark collapsed={collapsed} />
                    {sideMenu('dark')}
                </Sider>
            )}

            <Layout className="admin-layout__main">
                <Header className="admin-layout__header">
                    <div className="admin-layout__header-left">
                        <Button
                            type="text"
                            className="admin-layout__trigger"
                            icon={
                                isMobile || collapsed ? (
                                    <MenuUnfoldOutlined />
                                ) : (
                                    <MenuFoldOutlined />
                                )
                            }
                            onClick={() => {
                                if (isMobile) {
                                    setMobileOpen(true)
                                } else {
                                    toggleCollapsed()
                                }
                            }}
                        />
                        <div className="admin-layout__header-titles">
                            <Typography.Text className="admin-layout__header-title">
                                React 框架示例
                            </Typography.Text>
                            <Typography.Text className="admin-layout__header-desc">
                                前端工程化模板
                            </Typography.Text>
                        </div>
                    </div>
                </Header>

                <Content className="admin-layout__content">
                    <Outlet />
                </Content>
            </Layout>

            <Drawer
                title="菜单"
                placement="left"
                open={isMobile && mobileOpen}
                onClose={() => setMobileOpen(false)}
                styles={{ body: { padding: 0 } }}
                size={260}>
                <div className="admin-layout__drawer">
                    <BrandMark />
                    <div className="admin-layout__drawer-menu">{sideMenu('light')}</div>
                </div>
            </Drawer>
        </Layout>
    )
}
